version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='iplstats'
      - MYSQL_USER='netra'
      - MYSQL_PASSWORD='fixstream'
      - MYSQL_ROOT_PASSWORD='fixstream'
      - MYSQL_HOST=''
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db

