# Generated by Django 3.2.6 on 2021-08-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('date', models.DateField()),
                ('toss_decision', models.CharField(choices=[('FIELD', 'Field'), ('BAT', 'Bat')], max_length=10)),
                ('result', models.CharField(choices=[('NO_RESULT', 'No Result'), ('TIE', 'Tie'), ('NORMAL', 'Normal')], max_length=15)),
                ('dl_applied', models.BooleanField()),
                ('win_by_runs', models.CharField(blank=True, max_length=10, null=True)),
                ('win_by_wickets', models.CharField(blank=True, max_length=10, null=True)),
                ('player_of_match', models.CharField(blank=True, max_length=50, null=True)),
                ('umpire1', models.CharField(max_length=50)),
                ('umpire2', models.CharField(max_length=50)),
                ('umpire3', models.CharField(max_length=50)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='iplstats.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='iplstats.team')),
                ('toss_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toss_winner', to='iplstats.team')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplstats.venue')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to='iplstats.team')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField(choices=[(1, 'First'), (2, 'Second')])),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=50)),
                ('non_striker', models.CharField(max_length=50)),
                ('bowler', models.CharField(max_length=50)),
                ('is_super_over', models.BooleanField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(blank=True, max_length=50, null=True)),
                ('dismissal_kind', models.CharField(choices=[('CAUGHT', 'caught'), ('BOWLED', 'bowled'), ('LBW', 'lbw'), ('C&B', 'Caught and Bowled'), ('RUN_OUT', 'Run Out'), ('STUMPED', 'stumped')], max_length=50)),
                ('fielder', models.CharField(max_length=50)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_team', to='iplstats.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_team', to='iplstats.team')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplstats.match')),
            ],
        ),
    ]
